### Numpy Mastery Assignment 
 #### (Emefa Duah)
 

- Answer all questions


1. Create a 1D array of numbers from 0 to 9

In [2]:
import numpy as np
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3x3 numpy of all True 

In [6]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [10]:
array1 = np.arange(20,40)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [15]:
array1[array1%2 ==1] = -1
array1

array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

In [13]:
odd = array1%2 == 1
array1[odd] = -1
array1

array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

5. Create two arrays of length 10 and print out  common items in both arrays

In [25]:
a = np.arange(0, 11)
print(a)
b = np.arange(0, 21, 2)
print(b)

x= np.intersect1d(a,b)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 0  2  4  6  8 10]


6.  Create a 5x5 identity matrix

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [29]:
x = np.array([10, 12,9, 2, 20])
print(x)

y = np.linspace(10, 20, 101)
print(y)

z = np.ones((2,3))
print(z)

[10 12  9  2 20]
[10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9 20. ]
[[1. 1. 1.]
 [1. 1. 1.]]


8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [32]:
q= np.average(x)
print(q)

st = np.std(x)
print(st)

x = np.sort(x)
print(x)

10.6
5.782732917920384
[ 2  9 10 12 20]


9. Create a 10x10 array with random values and find the minimum and maximum values

In [37]:
np.full((10,10), 2)

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [39]:
p = np.random.randint(0, 100, size = (10,10))
maxi = np.max(p)
print(maxi)
mini = np.min(p)
print(mini)


98
1


10. Create a 3x3 matrix with values ranging from 0 to 8

In [41]:
m = np.arange(0, 9)
mat = m.reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


11.  Generates an array [[1 2 3] [4 5 6]]

In [50]:
lst = [1,2,3,4,5,6]
arr = np.array(lst)
t = arr.reshape(2,3)
print(t)

[[1 2 3]
 [4 5 6]]


12. Generates an array [0 2.5 5 7.5 10]

In [49]:
np.linspace(0,10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

13. Generates an 3x3 array of zeros

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. Create array from 0.1 to 10 with 12 elements, inclusively

In [43]:
np.linspace(0.1, 10,12)

array([ 0.1,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. ])

15. Create a matrix with seven columns and five rows of ten(10).

In [52]:
np.full((5,7), 10)

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

16. What is the difference between numpy and list?

Lists can contain different types of elements, in numpy arrays all the elements must have the same type.

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [59]:
b = np.full((50,), 1) #
print(b)

x = np.resize([1,0], 50)
print(x)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0]


18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [69]:
matrix = np.zeros((10,10))
print(matrix)

iden = np.fill_diagonal(matrix,1)
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [70]:
matrix1 = np.zeros((10,10))
print(matrix1)
np.fill_diagonal(matrix1, 0.1)
print(matrix1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.1 0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.1 0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.1 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.1 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.1 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.1 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.1 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.1 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.1 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.1]]


20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [90]:
a =np.array([[1,2],[3,4]])
print(a)
b =np.array([[5,6], [7,8]])
print(b)

z = np.dot(a,b)
print(z)

q = a@b
print(q)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [79]:
a =np.array([[1,2],[3,4]])
print(a)
b =np.array([[5,6], [7,8]])
print(b)

b = a*b
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]


22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [80]:
a =np.array([[1,2],[3,4]])
w = a*5
w

array([[ 5, 10],
       [15, 20]])

23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

In [91]:
A = np.array([[1,2],[3,4]])
B = A.transpose()

R = A*B
print(R)

[[ 1  6]
 [ 6 16]]


24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [87]:
A= np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

C = A*B
print(C)

D = B*A
print(D)

if C.all() == D.all():
    print("Yes, A x B = B x A")

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
Yes, A x B = B x A


25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [3]:
arr= np.array([[0, 1, 2] ,[3, 4, 5]])
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
A = arr[0,:]
A

array([0, 1, 2])

In [6]:
B = arr[1,:]
B

array([3, 4, 5])

In [8]:
C=arr[:,1]
C

array([1, 4])

In [9]:
D=arr[0,2]
D

2